### ISSUE TITLE
gallery-foogallery-slick-slider-sync.js

### ISSUE THREAD

**Issue by billrw3** [wptailor/foogallery-slick-template#1]
what's intended to be in this file? right now it's just the name to gallery-fooogaller-slick.js

**Comment by entr** [comment]
This is an extension for https://github.com/fooplugins/foogallery plugin that integrates slick carousel. It's quite basic though, far from stable or complete. Not sure if that was what you're asking about.

**Comment by billrw3** [comment]
The contents of https://github.com/wptailor/foogallery-slick-template/blob/master/js/gallery-foogallery-slick-slider-sync.js is just a filename, rather than code. I was just wondering if that was what was intended, or if it was a code overwrite.

**Comment by entr** [comment]
Oh, I see. It's a symlink to `gallery-foogallery-slick.js`. We don't actually need this file but FooGallery is auto enqueuing that path (based on gallery template slug). That's why we simply symlink `gallery-foogallery-slick.js` to `gallery-foogallery-slick-slider-sync.js`. We could change this since it works only on unix systems.

**Comment by entr** [comment]
Closing for now.
